### ISSUE TITLE
RuntimeError at /auth 

### ISSUE THREAD

**Issue by RadicalBlue** [Meshiest/mrseedbox#6]
Hi,
I'm really interested in your seedbox, so I tried to install it. But when I tried to connect to the seedbox I run into an error : 

> RuntimeError at /auth
> You must specify the NGINX_PORT env variable. 

The log says : 
 ```
https://domain.com/ -> /auth
172.17.0.7 - - [19/Mar/2017:09:41:59 UTC] "GET / HTTP/1.0" 200 1418
- -> /
2017-03-19 09:42:08 - RuntimeError - You must specify the NGINX_PORT env variable:
        /app/app.rb:19:in `envRequire'
        /app/app.rb:234:in `redirect_uri'
        /app/app.rb:1378:in `block in <class:Server>'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
        /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /usr/local/bundle/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
        /usr/local/bundle/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
        /usr/local/bundle/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
        /usr/local/bundle/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
        /usr/local/bundle/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
        /usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
        /usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
        /usr/local/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'
```
Did I do something wrong ?

Thanks

**Comment by Meshiest** [comment]
~~Can you post your docker-compose.yml?~~

Add `NGINX_PORT=443` to your common.env

Thanks!

**Comment by RadicalBlue** [comment]
It works ! 

Thanks !
